"""MTG multilingual term dictionary.

Maps German MTG terms to English equivalents so that type-line and
oracle-text searches work regardless of input language.

Public API:
  translate(term)   → English string or None
  expand_term(term) → [original] or [original, english] for SQL LIKE queries

Multi-word inputs ("legendäre kreatur") are handled by word-by-word fallback
so compound phrases translate correctly even without a phrase-level entry.
"""
from __future__ import annotations

# ── German → English ──────────────────────────────────────────────────────────
_DE: dict[str, str] = {

    # ── Card types ────────────────────────────────────────────────────────────
    "kreatur":                  "creature",
    "kreaturen":                "creature",
    "zauberei":                 "sorcery",
    "zaubereien":               "sorcery",
    "spontanzauber":            "instant",
    "spontanzaubers":           "instant",
    "verzauberung":             "enchantment",
    "verzauberungen":           "enchantment",
    "artefakt":                 "artifact",
    "artefakte":                "artifact",
    "artefakten":               "artifact",
    "planeswalker":             "planeswalker",
    "land":                     "land",
    "länderei":                 "land",
    "ländereien":               "land",
    "stammesmagie":             "tribal",
    "abenteuer":                "adventure",
    "saga":                     "saga",
    "sagas":                    "saga",
    "klasse":                   "class",
    "dungeon":                  "dungeon",
    "zimmer":                   "room",
    "fall":                     "case",

    # ── Supertypes ────────────────────────────────────────────────────────────
    "legendär":                 "legendary",
    "legendäre":                "legendary",
    "legendäres":               "legendary",
    "legendären":               "legendary",
    "legendärer":               "legendary",
    "legendärem":               "legendary",
    "basis":                    "basic",
    "grundland":                "basic land",
    "grundländerei":            "basic land",
    "schnee":                   "snow",
    "welt":                     "world",

    # ── Basic land subtypes ───────────────────────────────────────────────────
    "ebene":                    "plains",
    "ebenen":                   "plains",
    "insel":                    "island",
    "inseln":                   "island",
    "sumpf":                    "swamp",
    "sümpfe":                   "swamp",
    "berg":                     "mountain",
    "berge":                    "mountain",
    "wald":                     "forest",
    "wälder":                   "forest",

    # ── Other land subtypes ───────────────────────────────────────────────────
    "festung":                  "stronghold",
    "turm":                     "tower",
    "türme":                    "tower",
    "höhle":                    "cave",
    "höhlen":                   "cave",
    "burg":                     "castle",
    "mine":                     "mine",
    "minen":                    "mine",
    "stadt":                    "city",
    "städte":                   "city",
    "lager":                    "camp",
    "ruine":                    "ruin",
    "ruinen":                   "ruin",
    "tor":                      "gate",
    "tore":                     "gate",
    "hain":                     "grove",
    "haine":                    "grove",

    # ── Creature subtypes ─────────────────────────────────────────────────────
    "engel":                    "angel",
    "erzengel":                 "archangel",
    "dämon":                    "demon",
    "dämonen":                  "demon",
    "teufel":                   "devil",
    "teufel":                   "devil",
    "teufelchen":               "imp",
    "drache":                   "dragon",
    "drachen":                  "dragon",
    "zombie":                   "zombie",
    "zombies":                  "zombie",
    "skelett":                  "skeleton",
    "skelette":                 "skeleton",
    "vampir":                   "vampire",
    "vampire":                  "vampire",
    "vampiren":                 "vampire",
    "werwolf":                  "werewolf",
    "werwölfe":                 "werewolf",
    "wolf":                     "wolf",
    "wölfe":                    "wolf",
    "goblin":                   "goblin",
    "goblins":                  "goblin",
    "elfe":                     "elf",
    "elfen":                    "elf",
    "zauberer":                 "wizard",
    "zaubererin":               "wizard",
    "hexer":                    "warlock",
    "hexe":                     "witch",
    "hexen":                    "witch",
    "ritter":                   "knight",
    "soldat":                   "soldier",
    "soldaten":                 "soldier",
    "krieger":                  "warrior",
    "kriegerin":                "warrior",
    "kriegerinnen":             "warrior",
    "priester":                 "cleric",
    "priesterin":               "cleric",
    "druide":                   "druid",
    "druiden":                  "druid",
    "schurke":                  "rogue",
    "schurken":                 "rogue",
    "schurkin":                 "rogue",
    "schamane":                 "shaman",
    "schamanen":                "shaman",
    "barbar":                   "barbarian",
    "barbarin":                 "barbarian",
    "bestie":                   "beast",
    "bestien":                  "beast",
    "riese":                    "giant",
    "riesen":                   "giant",
    "golem":                    "golem",
    "golems":                   "golem",
    "geist":                    "spirit",
    "geister":                  "spirit",
    "gespenst":                 "specter",
    "gespenster":               "specter",
    "phantom":                  "shade",
    "schatten":                 "shade",
    "phönix":                   "phoenix",
    "hydra":                    "hydra",
    "hydren":                   "hydra",
    "sphinx":                   "sphinx",
    "sphinxe":                  "sphinx",
    "vogel":                    "bird",
    "vögel":                    "bird",
    "insekt":                   "insect",
    "insekten":                 "insect",
    "spinne":                   "spider",
    "spinnen":                  "spider",
    "schlange":                 "snake",
    "schlangen":                "snake",
    "mensch":                   "human",
    "menschen":                 "human",
    "zwerg":                    "dwarf",
    "zwerge":                   "dwarf",
    "ork":                      "orc",
    "orks":                     "orc",
    "gnom":                     "gnome",
    "gnome":                    "gnome",
    "troll":                    "troll",
    "trolle":                   "troll",
    "oger":                     "ogre",
    "kobold":                   "kobold",
    "kobolde":                  "kobold",
    "faun":                     "satyr",
    "satyr":                    "satyr",
    "satyren":                  "satyr",
    "nymphe":                   "nymph",
    "nymphen":                  "nymph",
    "einhorn":                  "unicorn",
    "einhörner":                "unicorn",
    "pegasus":                  "pegasus",
    "meerjungfrau":             "merfolk",
    "nixe":                     "merfolk",
    "nixenfolk":                "merfolk",
    "minotaurus":               "minotaur",
    "minotauren":               "minotaur",
    "zentaur":                  "centaur",
    "zentauren":                "centaur",
    "zyklop":                   "cyclops",
    "zykloppe":                 "cyclops",
    "gorgone":                  "gorgon",
    "gorgonen":                 "gorgon",
    "basilisk":                 "basilisk",
    "basilisken":               "basilisk",
    "elementar":                "elemental",
    "elementare":               "elemental",
    "elementaren":              "elemental",
    "avatar":                   "avatar",
    "avatare":                  "avatar",
    "konstrukt":                "construct",
    "konstrukte":               "construct",
    "homunkulus":               "homunculus",
    "homunkuli":                "homunculus",
    "horror":                   "horror",
    "illusion":                 "illusion",
    "illusionen":               "illusion",
    "berserker":                "berserker",
    "gestaltwandler":           "shapeshifter",
    "eldrazi":                  "eldrazi",
    "phyrexianer":              "phyrexian",
    "ratte":                    "rat",
    "ratten":                   "rat",
    "katze":                    "cat",
    "katzen":                   "cat",
    "hund":                     "dog",
    "hunde":                    "dog",
    "bär":                      "bear",
    "bären":                    "bear",
    "löwe":                     "lion",
    "löwen":                    "lion",
    "tiger":                    "tiger",
    "hai":                      "shark",
    "haie":                     "shark",
    "oktopus":                  "octopus",
    "krake":                    "kraken",
    "leviathan":                "leviathan",
    "seeungeheuer":             "sea monster",
    "wal":                      "whale",
    "wale":                     "whale",
    "krokodil":                 "crocodile",
    "krokodile":                "crocodile",
    "schildkröte":              "turtle",
    "frosch":                   "frog",
    "frösche":                  "frog",
    "pflanze":                  "plant",
    "pflanzen":                 "plant",
    "pilz":                     "fungus",
    "pilze":                    "fungus",
    "baumvolk":                 "treefolk",
    "waldbewohner":             "treefolk",
    "loxodon":                  "elephant",
    "elefant":                  "elephant",
    "elefanten":                "elephant",
    "nashorn":                  "rhino",
    "nashörner":                "rhino",
    "kirin":                    "kirin",
    "vedalken":                 "vedalken",
    "leonin":                   "cat",
    "kor":                      "kor",
    "viashino":                 "viashino",
    "goblin":                   "goblin",
    "vampire":                  "vampire",
    "gnoll":                    "gnoll",
    "teufelchen":               "imp",
    "teufelsbande":             "devil",
    "nachtalb":                 "nightmare",
    "einäuger":                 "cyclops",
    "echse":                    "lizard",
    "echsen":                   "lizard",
    "skorpion":                 "scorpion",
    "skorpione":                "scorpion",
    "krabbe":                   "crab",
    "krabben":                  "crab",
    "qualle":                   "jellyfish",
    "libelle":                  "insect",
    "käfer":                    "insect",
    "spinne":                   "spider",
    "adler":                    "bird",
    "eule":                     "bird",
    "falke":                    "bird",
    "rabe":                     "bird",
    "raben":                    "bird",
    "drache":                   "dragon",
    "wyrm":                     "wurm",
    "würmer":                   "wurm",
    "schleim":                  "ooze",
    "schleime":                 "ooze",
    "tier":                     "animal",
    "tiere":                    "animal",
    "jäger":                    "hunter",
    "jägerin":                  "hunter",
    "forscher":                 "scout",
    "späher":                   "scout",
    "spähin":                   "scout",
    "alchemist":                "wizard",
    "chronist":                 "advisor",
    "berater":                  "advisor",
    "händler":                  "merchant",
    "pirat":                    "pirate",
    "piraten":                  "pirate",
    "piratIn":                  "pirate",
    "architekt":                "artificer",
    "tüftler":                  "artificer",
    "hexenmeister":             "warlock",
    "beschwörer":               "shaman",
    "kleriker":                 "cleric",
    "hohepriester":             "cleric",
    "söldner":                  "mercenary",
    "söldnerin":                "mercenary",
    "hauptmann":                "soldier",
    "offizier":                 "soldier",
    "general":                  "soldier",
    "admiral":                  "pirate",
    "bürger":                   "citizen",
    "bürgerinnen":              "citizen",
    "bauer":                    "peasant",
    "bauern":                   "peasant",
    "adliger":                  "noble",
    "adeliger":                 "noble",
    "könig":                    "noble",
    "königin":                  "noble",
    "prinz":                    "noble",
    "prinzessin":               "noble",
    "abenteurer":               "scout",
    "abenteurerin":             "scout",
    "dorf":                     "village",
    "held":                     "hero",
    "heldin":                   "hero",
    "helden":                   "hero",
    "schurkin":                 "rogue",

    # ── Artifact subtypes ─────────────────────────────────────────────────────
    "ausrüstung":               "equipment",
    "fahrzeug":                 "vehicle",
    "fahrzeuge":                "vehicle",
    "schiff":                   "vehicle",
    "schiffe":                  "vehicle",

    # ── Enchantment subtypes ──────────────────────────────────────────────────
    "aura":                     "aura",
    "auran":                    "aura",
    "schrein":                  "shrine",
    "schreine":                 "shrine",
    "siegel":                   "rune",
    "beschwörungskreis":        "circle",

    # ── Planeswalker subtypes (unchanged across languages) ────────────────────
    "ajani":    "ajani",   "chandra":  "chandra",  "garruk":   "garruk",
    "gideon":   "gideon",  "jace":     "jace",     "liliana":  "liliana",
    "nissa":    "nissa",   "sorin":    "sorin",    "tamiyo":   "tamiyo",
    "teferi":   "teferi",  "tibalt":   "tibalt",   "vraska":   "vraska",
    "karn":     "karn",    "ugin":     "ugin",     "ashiok":   "ashiok",
    "elspeth":  "elspeth", "nahiri":   "nahiri",   "lolth":    "lolth",
    "tezzeret": "tezzeret","domri":    "domri",    "arlinn":   "arlinn",
    "angrath":  "angrath", "huatli":   "huatli",   "saheeli":  "saheeli",
    "vivien":   "vivien",  "kasmina":  "kasmina",  "lukka":    "lukka",
    "basri":    "basri",   "zariel":   "zariel",   "mordenkainen": "mordenkainen",

    # ── Keywords – evergreen ──────────────────────────────────────────────────
    "flugfähigkeit":            "flying",
    "fliegen":                  "flying",
    "flug":                     "flying",
    "erster angriff":           "first strike",
    "erste angriff":            "first strike",
    "erstangriff":              "first strike",
    "doppelter angriff":        "double strike",
    "doppelangriff":            "double strike",
    "eile":                     "haste",
    "unverwundbarkeit":         "indestructible",
    "unverwundbar":             "indestructible",
    "reichweite":               "reach",
    "wachsamkeit":              "vigilance",
    "trampeln":                 "trample",
    "bedrohung":                "menace",
    "lebensbindung":            "lifelink",
    "todesberührung":           "deathtouch",
    "hexensicher":              "hexproof",
    "undurchdringbar":          "shroud",
    "schutz":                   "protection",
    "unblockierbar":            "unblockable",
    "provozieren":              "provoke",
    "aufblitzen":               "flash",
    "tarnung":                  "shadow",
    "flankieren":               "flanking",
    "wüten":                    "rampage",
    "kampfschrei":              "battle cry",
    "exaliert":                 "exalted",
    "heldenmut":                "banding",
    "landgang":                 "landwalk",
    "sumpfgang":                "swampwalk",
    "waldgang":                 "forestwalk",
    "inselgang":                "islandwalk",
    "berggang":                 "mountainwalk",
    "ebenenwalk":               "plainswalk",
    "angst":                    "fear",
    "einschüchterung":          "intimidate",
    "flugangst":                "flying",
    "verborgen":                "shroud",
    "schadensvorbeugung":       "damage prevention",

    # ── Keywords – non-evergreen / returning mechanics ────────────────────────
    "zyklus":                   "cycling",
    "land-zyklus":              "landcycling",
    "basis-land-zyklus":        "basic landcycling",
    "rückruf":                  "flashback",
    "nachwirkung":              "aftermath",
    "kicker":                   "kicker",
    "aufgewertet":              "kicked",
    "multikicker":              "multikicker",
    "überladen":                "overload",
    "aufstieg":                 "ascend",
    "stadtssegen":              "city's blessing",
    "auftauchen":               "emerge",
    "verwandeln":               "transform",
    "verwandelt":               "transformed",
    "doppelgesichtig":          "double-faced",
    "vertiefung":               "delve",
    "begeisterung":             "devotion",
    "beschwören":               "convoke",
    "eskalation":               "escalate",
    "gedeihen":                 "proliferate",
    "entfesseln":               "unleash",
    "aufbruch":                 "dash",
    "exploit":                  "exploit",
    "renommee":                 "renown",
    "geschicklichkeit":         "prowess",
    "erkundung":                "explore",
    "überleben":                "persist",
    "zähigkeit":                "undying",
    "auferstehung":             "unearth",
    "scavenge":                 "scavenge",
    "detektivarbeit":           "investigate",
    "hinweis":                  "clue",
    "hinweise":                 "clue",
    "mutieren":                 "mutate",
    "mutiert":                  "mutated",
    "begleiter":                "companion",
    "foretell":                 "foretell",
    "voraussagen":              "foretell",
    "ankündigen":               "foretell",
    "boast":                    "boast",
    "prahlen":                  "boast",
    "ausrüsten":                "equip",
    "ausgerüstet":              "equipped",
    "befestigen":               "fortify",
    "verwandeln":               "transform",
    "morph":                    "morph",
    "megamorph":                "megamorph",
    "manifest":                 "manifest",
    "manifestieren":            "manifest",
    "verzaubern":               "enchant",
    "verzaubert":               "enchanted",
    "kanalisieren":             "channel",
    "kanalisation":             "channel",
    "verschmelzen":             "fuse",
    "überfluten":               "overrun",
    "entwässern":               "tap",
    "reanimieren":              "reanimate",
    "wiederbeleben":            "return from graveyard",
    "ausspielen":               "cast",
    "ausspielen von":           "cast",
    "überlisten":               "outwit",
    "gegenzauber":              "counterspell",
    "entkräften":               "counter",
    "vernichten":               "destroy",
    "auflösen":                 "dissolve",
    "abblocken":                "block",
    "abwehren":                 "prevent",
    "absorb":                   "absorb",
    "bürgschaft":               "tribute",
    "tribut":                   "tribute",
    "überrennen":               "overwhelm",
    "überwältigen":             "overwhelm",
    "beleuchten":               "illuminate",
    "nachäffen":                "copy",
    "verdoppeln":               "double",
    "spiegeln":                 "mirror",
    "amass":                    "amass",
    "aufmarsch":                "amass",
    "adaptieren":               "adapt",
    "anpassen":                 "adapt",
    "rekrutieren":              "enlist",
    "einberufen":               "enlist",
    "trainieren":               "train",
    "saddlen":                  "saddle",
    "reiten":                   "saddle",
    "aufwachsen":               "level up",
    "stärken":                  "reinforce",
    "stärkung":                 "reinforce",
    "verwüsten":                "devastate",
    "tribute":                  "tribute",
    "anwerben":                 "recruit",
    "zermahlen":                "grind",
    "mahlen":                   "mill",
    "fräsen":                   "mill",
    "erinnerung":               "flashback",
    "blutrausch":               "bloodthirst",
    "seelenbindung":            "soulbond",
    "inspirieren":              "inspire",
    "entzücken":                "enrapture",
    "begeistern":               "inspire",
    "ninjutsu":                 "ninjutsu",
    "bushido":                  "bushido",
    "soulshift":                "soulshift",
    "offering":                 "offering",
    "splice":                   "splice",
    "splicen":                  "splice",
    "affinity":                 "affinity",
    "affinität":                "affinity",
    "modular":                  "modular",
    "imprint":                  "imprint",
    "einprägen":                "imprint",
    "haunt":                    "haunt",
    "heimsuchen":               "haunt",
    "transmute":                "transmute",
    "transmutieren":            "transmute",
    "bloodthirst":              "bloodthirst",
    "graft":                    "graft",
    "pfropfen":                 "graft",
    "forecast":                 "forecast",
    "vorhersagen":              "forecast",
    "hellseher":                "forecast",
    "ripple":                   "ripple",
    "wellen":                   "ripple",
    "suspend":                  "suspend",
    "aussetzen":                "suspend",
    "morph":                    "morph",
    "echo":                     "echo",
    "cumulative upkeep":        "cumulative upkeep",
    "phasing":                  "phasing",
    "buyback":                  "buyback",
    "storm":                    "storm",
    "sturm":                    "storm",
    "dredge":                   "dredge",
    "baggern":                  "dredge",
    "hellbent":                 "hellbent",
    "threshold":                "threshold",
    "schwellenwert":            "threshold",
    "madness":                  "madness",
    "wahnsinn":                 "madness",
    "delirium":                 "delirium",
    "morbid":                   "morbid",
    "fateful hour":             "fateful hour",
    "schicksalsstunde":         "fateful hour",
    "overrun":                  "overrun",
    "conspire":                 "conspire",
    "verschwören":              "conspire",
    "reinforce":                "reinforce",
    "persist":                  "persist",
    "undying":                  "undying",
    "miracle":                  "miracle",
    "wunder":                   "miracle",
    "cipher":                   "cipher",
    "chiffrieren":              "cipher",
    "extort":                   "extort",
    "blutzoll":                 "extort",
    "fuse":                     "fuse",
    "battalion":                "battalion",
    "battalion":                "battalion",
    "skulk":                    "skulk",
    "schleichen":               "skulk",
    "menace":                   "menace",
    "revolt":                   "revolt",
    "aufstand":                 "revolt",
    "hidden agenda":            "hidden agenda",
    "improvise":                "improvise",
    "improvisieren":            "improvise",
    "aftermath":                "aftermath",
    "cycling":                  "cycling",
    "embalm":                   "embalm",
    "einbalsamieren":           "embalm",
    "eternalize":               "eternalize",
    "verewigen":                "eternalize",
    "exert":                    "exert",
    "anstrengen":               "exert",
    "afflict":                  "afflict",
    "quälen":                   "afflict",
    "ingest":                   "ingest",
    "verschlucken":             "ingest",
    "cohort":                   "cohort",
    "kohorte":                  "cohort",
    "surge":                    "surge",
    "schwall":                  "surge",
    "support":                  "support",
    "unterstützen":             "support",
    "assist":                   "assist",
    "helfen":                   "assist",
    "goad":                     "goad",
    "antreiben":                "goad",
    "mentor":                   "mentor",
    "spectacle":                "spectacle",
    "spektakel":                "spectacle",
    "jump-start":               "jump-start",
    "neustarten":               "jump-start",
    "undergrowth":              "undergrowth",
    "verwurzelung":             "undergrowth",
    "riot":                     "riot",
    "krawall":                  "riot",
    "convoke":                  "convoke",
    "einberufung":              "convoke",
    "populate":                 "populate",
    "bevölkern":                "populate",
    "detain":                   "detain",
    "festhalten":               "detain",
    "overload":                 "overload",
    "scry":                     "scry",
    "wahrsagen":                "scry",
    "surveil":                  "surveil",
    "überwachen":               "surveil",
    "learn":                    "learn",
    "lernen":                   "learn",
    "ward":                     "ward",
    "schutzaura":               "ward",
    "shield":                   "shield",
    "schild":                   "shield",
    "disturb":                  "disturb",
    "stören":                   "disturb",
    "cleave":                   "cleave",
    "spalten":                  "cleave",
    "training":                 "training",
    "compleation":              "compleation",
    "read ahead":               "read ahead",
    "vorauslesen":              "read ahead",
    "backup":                   "backup",
    "sichern":                  "backup",
    "hideaway":                 "hideaway",
    "versteck":                 "hideaway",
    "discover":                 "discover",
    "entdecken":                "discover",
    "craft":                    "craft",
    "herstellen":               "craft",
    "offspring":                "offspring",
    "nachkomme":                "offspring",
    "gift":                     "gift",
    "geschenk":                 "gift",
    "plot":                     "plot",
    "anschlag":                 "plot",
    "spree":                    "spree",
    "eskalieren":               "spree",
    "impending":                "impending",
    "drohend":                  "impending",

    # ── Zones / game objects ──────────────────────────────────────────────────
    "schlachtfeld":             "battlefield",
    "friedhof":                 "graveyard",
    "exil":                     "exile",
    "hand":                     "hand",
    "bibliothek":               "library",
    "stapel":                   "stack",
    "befehlszone":              "command zone",
    "seitenboard":              "sideboard",
    "seitenblatt":              "sideboard",
    "spielfeld":                "battlefield",
    "tabletop":                 "battlefield",

    # ── Token types ───────────────────────────────────────────────────────────
    "spielstein":               "token",
    "spielsteine":              "token",
    "token":                    "token",
    "tokens":                   "token",
    "kopie":                    "copy",
    "kopien":                   "copy",

    # ── Counters ──────────────────────────────────────────────────────────────
    "zähler":                   "counter",
    "zählers":                  "counter",
    "+1/+1-zähler":             "+1/+1 counter",
    "-1/-1-zähler":             "-1/-1 counter",
    "loyalitätszähler":         "loyalty counter",
    "giftzähler":               "poison counter",
    "schicksalszähler":         "fate counter",
    "zeitzähler":               "time counter",
    "ladungszähler":            "charge counter",
    "stärkungszähler":          "+1/+1 counter",
    "schwächungszähler":        "-1/-1 counter",
    "erfahrungszähler":         "experience counter",
    "energiemarker":            "energy counter",
    "energie":                  "energy",

    # ── Mana / mana costs ─────────────────────────────────────────────────────
    "mana":                     "mana",
    "manabasis":                "mana base",
    "manakosten":               "mana cost",
    "umgewandelte manakosten":  "converted mana cost",
    "manawert":                 "mana value",
    "generisches mana":         "generic mana",
    "farblos":                  "colorless",
    "farbloses":                "colorless",
    "mehrfarbig":               "multicolored",
    "bunt":                     "multicolored",
    "hybrid":                   "hybrid",
    "phyrexianisch":            "phyrexian",
    "weiß":                     "white",
    "weißes":                   "white",
    "blau":                     "blue",
    "blaues":                   "blue",
    "schwarz":                  "black",
    "schwarzes":                "black",
    "rot":                      "red",
    "rotes":                    "red",
    "grün":                     "green",
    "grünes":                   "green",

    # ── Oracle-text actions ───────────────────────────────────────────────────
    "zerstöre":                 "destroy",
    "zerstört":                 "destroy",
    "zerstören":                "destroy",
    "verbannen":                "exile",
    "verbannt":                 "exiled",
    "ins exil schicken":        "exile",
    "ins exil legen":           "exile",
    "ins exil":                 "exile",
    "ziehe":                    "draw",
    "zieht":                    "draws",
    "ziehen":                   "draw",
    "karte":                    "card",
    "karten":                   "cards",
    "lebenspunkte":             "life",
    "lebenspunkt":              "life",
    "leben":                    "life",
    "angreifen":                "attack",
    "angreifer":                "attacker",
    "angreifend":               "attacking",
    "angreifenden":             "attacking",
    "blockieren":               "block",
    "blockiert":                "blocked",
    "blocker":                  "blocker",
    "blockierend":              "blocking",
    "schaden":                  "damage",
    "kampfschaden":             "combat damage",
    "tappt":                    "tap",
    "enttappt":                 "untap",
    "getappt":                  "tapped",
    "ungetappt":                "untapped",
    "aktiviere":                "activate",
    "aktiviert":                "activated",
    "ausgelöst":                "triggered",
    "auslöst":                  "triggers",
    "statisch":                 "static",
    "durchsuche":               "search",
    "suche":                    "search",
    "durchsuchst":              "search",
    "mische":                   "shuffle",
    "mischst":                  "shuffle",
    "aufgedeckt":               "revealed",
    "aufdecken":                "reveal",
    "abwerfen":                 "discard",
    "abwirft":                  "discards",
    "opfere":                   "sacrifice",
    "geopfert":                 "sacrificed",
    "zurückgeben":              "return",
    "auf die hand":             "to hand",
    "auf den friedhof":         "to graveyard",
    "auf das schlachtfeld":     "onto the battlefield",
    "wirken":                   "cast",
    "erzeugt":                  "create",
    "erzeuge":                  "create",
    "lege":                     "put",
    "gelegt":                   "put",
    "verdopple":                "double",
    "gewinne":                  "gain",
    "verliere":                 "lose",
    "zahle":                    "pay",
    "bezahle":                  "pay",
    "kostet":                   "costs",
    "kosten":                   "cost",
    "reduziere":                "reduce",
    "addiere":                  "add",
    "steuerung":                "control",
    "kontrollierst":            "control",
    "kontrolliert":             "controls",
    "zielst":                   "target",
    "ziel":                     "target",
    "beliebiges ziel":          "any target",
    "wenn":                     "when",
    "wann immer":               "whenever",
    "solange":                  "as long as",
    "am beginn":                "at the beginning",
    "am ende":                  "at the end",
    "aufräumschritt":           "end step",
    "beginn des kampfes":       "beginning of combat",
    "endsegment":               "end step",
    "ziehschritt":              "draw step",
    "hauptphase":               "main phase",
    "kampfphase":               "combat phase",
    "enttappschritt":           "untap step",
    "versorgungsschritt":       "upkeep",
    "aufräumphase":             "cleanup step",

    # ── Miscellaneous game terms ───────────────────────────────────────────────
    "stärke":                   "power",
    "widerstandskraft":         "toughness",
    "loyalität":                "loyalty",
    "legendär":                 "legendary",
    "permanent":                "permanent",
    "permanente":               "permanent",
    "permanenten":              "permanent",
    "zauberspruch":             "spell",
    "zaubersprüche":            "spell",
    "fähigkeit":                "ability",
    "fähigkeiten":              "ability",
    "aktivierungsfähigkeit":    "activated ability",
    "ausgelöste fähigkeit":     "triggered ability",
    "statische fähigkeit":      "static ability",
    "verzauberungsfähigkeit":   "enchantment ability",
    "kreaturenfähigkeit":       "creature ability",
    "effekt":                   "effect",
    "effekte":                  "effect",
    "ergebnis":                 "result",
    "auflösung":                "resolution",
    "priorität":                "priority",
    "zug":                      "turn",
    "züge":                     "turn",
    "kampf":                    "combat",
    "spieler":                  "player",
    "spielerin":                "player",
    "gegner":                   "opponent",
    "gegnerin":                 "opponent",
    "kontrolleur":              "controller",
    "besitzer":                 "owner",
    "eigentümer":               "owner",
    "verdrängen":               "replace",
    "ersatzeffekt":             "replacement effect",
    "prävention":               "prevention",
    "schutzschild":             "protection",
    "blockiert von":            "blocked by",
    "ungeblockt":               "unblocked",
    "erster kampfschaden":      "first strike damage",
    "trampelschaden":           "trample damage",
    "lebenspunktegewinn":       "life gain",
    "lebenspunkteverlust":      "life loss",
    "ziehsperre":               "draw lock",
    "opfereffekt":              "sacrifice effect",
    "rückkehrkarte":            "return card",
    "abwurfkarte":              "discard card",
    "decken":                   "reveal",
    "aufdecken":                "reveal",
    "anschauen":                "look at",
    "vergräber":                "mill",
    "mühle":                    "mill",
    "mahlen":                   "mill",
    "vermahlen":                "mill",
    "friedhofseffekt":          "graveyard effect",
    "rückkehr aus dem friedhof": "return from graveyard",
    "todesauslöser":            "dies trigger",
    "stirbt":                   "dies",
    "sterben":                  "die",
    "gestorben":                "died",
    "erzeugen":                 "create",
    "token erzeugen":           "create token",
    "verdoppeln":               "double",
    "markierung":               "counter",
    "giftzähler erhalten":      "gets poison counter",
    "vergiftet":                "poisoned",
    "infiziert":                "infect",
    "infektion":                "infect",
    "verwelken":                "wither",
    "verwelkt":                 "withered",
    "gift":                     "poison",
    "giftmarker":               "poison counter",
    "proliferieren":            "proliferate",
    "verdrängen":               "replace",
}

# ── Combined lookup ────────────────────────────────────────────────────────────
_ALL: dict[str, str] = _DE


# ── Public API ─────────────────────────────────────────────────────────────────

def translate(term: str) -> str | None:
    """Return the English equivalent of *term* if known, else None."""
    return _ALL.get(term.lower().strip())


def expand_term(term: str) -> list[str]:
    """Return SQL LIKE search terms for *term*.

    Returns [term] when no translation is available.
    Returns [term, english] when a whole-phrase match is found.
    For multi-word input with no phrase match, tries word-by-word translation
    and returns [term, translated] if any word changes.
    """
    low = term.lower().strip()

    # 1. Whole-phrase lookup
    en = _ALL.get(low)
    if en and en != low:
        return [term, en]

    # 2. Word-by-word fallback for compound inputs ("legendäre kreatur" → "legendary creature")
    words = low.split()
    if len(words) > 1:
        translated_words = [_ALL.get(w, w) for w in words]
        translated = " ".join(translated_words)
        if translated != low:
            return [term, translated]

    return [term]
